<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NTB-257" failures="1" tests="2" name="Academy.Cucumber.TestNGTestRunner" time="29.702" errors="0" timestamp="2022-11-24T14:59:03 CET" skipped="0">
  <testcase classname="Academy.Cucumber.TestNGTestRunner" name="runScenario" time="24.242"/>
  <system-out/>
  <testcase classname="Academy.Cucumber.TestNGTestRunner" name="runScenario" time="5.460">
    <failure message="did not expect [JovanK] but found [JovanK]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect [JovanK] but found [JovanK]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at org.testng.Assert.assertNotEquals(Assert.java:2055)
at Academy.StepDefinitions.StepDefinition.verify_that_the_users_is_not_as_expected(StepDefinition.java:145)
at âœ½.Verify that the user's JovanK is not as expected(file:///C:/Users/joko2909/SeleniumTraining/Toma14112022/src/test/java/Academy/Cucumber/ErrorValidations.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Academy.Cucumber.TestNGTestRunner -->
