<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <listeners>
    <listener class-name="Academy.TestComponents.Listeners"/>
    <listener class-name="Academy.TestComponents.TestRetryAnalyzerListener"/>
  </listeners>
  <test thread-count="5" parallel="tests" name="StandAloneTest163ErrorValidations(failed)">
    <classes>
      <class name="Academy.TestCases.StandAloneTest163ErrorValidations">
        <methods>
          <include name="launchApplication"/>
          <include name="tearDown"/>
          <include name="wrongEmailLogin"/>
          <include name="wrongEmailLoginTestRetryAllFailedTestcases"/>
        </methods>
      </class> <!-- Academy.TestCases.StandAloneTest163ErrorValidations -->
    </classes>
  </test> <!-- StandAloneTest163ErrorValidations(failed) -->
</suite> <!-- Failed suite [Suite] -->
