<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NTB-257" failures="1" tests="2" name="Default test" time="30.905" errors="0" timestamp="2022-11-24T14:59:03 CET">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="24.242"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="5.46">
    <failure type="java.lang.AssertionError" message="did not expect [JovanK] but found [JovanK]">
      <![CDATA[java.lang.AssertionError: did not expect [JovanK] but found [JovanK]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1417)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2033)
at org.testng.Assert.assertNotEquals(Assert.java:2055)
at Academy.StepDefinitions.StepDefinition.verify_that_the_users_is_not_as_expected(StepDefinition.java:145)
at âœ½.Verify that the user's JovanK is not as expected(file:///C:/Users/joko2909/SeleniumTraining/Toma14112022/src/test/java/Academy/Cucumber/ErrorValidations.feature:24)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
